variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-all:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build && cd build
    - cmake ..
    - make
    - make fft1d_emu
    - make fft2d_ddr_emu
    - make fft2d_bram_emu
    - make fft3d_ddr_emu
    - make fft3d_bram_emu
    - chmod +x bin/host bin/test
  artifacts:
    paths:
      - build/bin/64_fft1d_emulate.aocx
      - build/bin/64_fft2d_bram_emulate.aocx
      - build/bin/64_fft2d_ddr_emulate.aocx
      - build/bin/64_fft3d_bram_emulate.aocx
      - build/bin/64_fft3d_ddr_emulate.aocx
      - build/bin/test
      - build/bin/host

test-all:
  stage: test
  script:
    - cd build/bin/
    - CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./test
  dependencies:
    - build-all